### ISSUE TITLE
[QA] Translations

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1574]
Missing translations:

Not a bug:

- [x] ["adjusted" starts with a lower case letter](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2098130285)

Checked and fixed [07.05.2024]:

Missing translations:

- [x] [Missing translation "Trusted all (recommended)](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2097944775)
- [x] [The word starts with a lower case letter.](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2095914638)
- [x] [Search for a tracker or organization](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2095721783)
- [x] [Enter website URL](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2095848305)
- [x] ["Tracker" translated into Polish](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2097911114)

UI:

- [ ]  [Two rows "Zablokowano na wszystkich stronach"](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2097909116) (edit: There is no way to make it so that there is one line. Whole the text is centred.)

Checked and will not be fixed [07.05.2024]:

- [ ] [All categories description](https://github.com/ghostery/ghostery-extension/issues/1574#issuecomment-2095727282)

**Comment by GRadziejewski** [comment]
Italian:

Open Trackers. There is "Search for a tracker or organization"
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/d4d6378b-cd75-4e77-ba9f-9a034d19f577)

**Comment by GRadziejewski** [comment]
Open Trackers. Move the mouse cursor over the ‘i’ icon to display the category description.
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/29a93d31-8d6a-46cc-8343-4d05aa1948e7)

**Comment by GRadziejewski** [comment]
Open Trackers. Open any description of the tracking programme. Click the ‘Add’ button to add an exception.
 There is "Enter website URL"

French:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/843c2ffd-7994-46d5-9a7a-7aaf1dc60423)

**Comment by GRadziejewski** [comment]
The word starts with a lower case letter.
French - `mouchards`:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/bfe7f251-7270-402c-8643-a30f3b1b713b)

**Comment by GRadziejewski** [comment]
Polish:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/d5db10e4-e1f0-45b1-a5e6-00891b569806)

**Comment by GRadziejewski** [comment]
"Tropiciele" instead of "Trackers"

Polish:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/73037005-f7be-431a-8448-f1a1c5627647)

**Comment by GRadziejewski** [comment]
"Trust all (recommend)"

Polish:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/77d1a309-7280-4641-b763-0c4aa1f914cc)

**Comment by GRadziejewski** [comment]
Open Trackers. Click on the dropdown menu 
The word "adjusted" starts with a lower case letter.

Polish:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/99999967-3910-4b0a-a2b2-7f959cd4fb49)
