### ISSUE TITLE
Support `$redirect` in DNR

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1714]
This is a Manifest V3 regression. 

Affected pages https://github.com/ghostery/broken-page-reports/issues/728

Redirect filters like `*.mp4$media,redirect=noopmp3-0.1s,domain=tubitv.com`
gets converted to DNR rules like
```
  {
    "id": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "extensionPath": "/web_accessible_resources/noopmp3.mp3"
      }
    },
    "condition": {
      "urlFilter": "*.mp4",
      "initiatorDomains": [
        "tubitv.com"
      ],
      "resourceTypes": [
        "media"
      ],
      "isUrlFilterCaseSensitive": false
    },
    "priority": 1301
  }
```

To make them run, the resources has to be shipped with the extension, while in Manifest v2 those could be downloaded in the runtime from https://cdn.ghostery.com/adblocker/resources/ublock-resources/6876912b29633b4bd229334f7d2e50dcd43eea0309e6414e0a17dbdb56142f8a/list.txt

Alternatively, the resources could be shipped in the ruleset, but it would likely blow up its size.
```[tasklist]
### Tasks
- [ ] Ensure the redirect rules are in the ruleset
- [ ] On build time copy resources to `/web_accessible_resources`
- [ ] Convert filename to matche the DNR converter
```
