### ISSUE TITLE
Decrease CDN downloads

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1844]
```[tasklist]
### Tasks
- [ ] Ask for Anti-Tracking `update.json` only once again
- [ ] Store checksum of adblocker engines to prevent unnecessary downloads
- [x] Prevent TrackerDB partial updates - only full updates can work
- [ ] Check for adblocker updates less often
- [x] Enable engine compression on the CDN
- [ ] Investigate "raced" HTTP requests - reduce their likelihood if they regularly happen (and does it explain duplicated requests in DevTools and mitm proxy?)
```

**Comment by smalluban** [comment]
I suggest to split the issue into atomic problems, which are still valid, and close this meta issue, as it hides the details, and it looks that it is a reason to not do anything with that lately.

**Comment by smalluban** [comment]
@chrmod @philipp-classen ping

**Comment by chrmod** [comment]
I would also say that current cost level is acceptable. Closing
